### ISSUE TITLE
Program stuck on loading.

### ISSUE THREAD

**Issue by enthalith** [Psycho-Marcus/WuWa_Inventory_Kamera#1]
Upon opening the program, it's stuck in loading, please wait.
[WuWaInventoryKamera.log](https://github.com/user-attachments/files/17185842/WuWaInventoryKamera.log)
[WuWaInventoryKamera.debug.log](https://github.com/user-attachments/files/17185843/WuWaInventoryKamera.debug.log)

**Comment by Psycho-Marcus** [comment]
Thanks for raising the issue, @enthalith. I'll upload a new release tomorrow, and it should be fixed
